// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// AnnouncementRead is the predicate function for announcementread builders.
type AnnouncementRead func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// IdempotencyRecord is the predicate function for idempotencyrecord builders.
type IdempotencyRecord func(*sql.Selector)

// PaymentAuditLog is the predicate function for paymentauditlog builders.
type PaymentAuditLog func(*sql.Selector)

// PaymentChannel is the predicate function for paymentchannel builders.
type PaymentChannel func(*sql.Selector)

// PaymentOrder is the predicate function for paymentorder builders.
type PaymentOrder func(*sql.Selector)

// PaymentProviderInstance is the predicate function for paymentproviderinstance builders.
type PaymentProviderInstance func(*sql.Selector)

// PromoCode is the predicate function for promocode builders.
type PromoCode func(*sql.Selector)

// PromoCodeUsage is the predicate function for promocodeusage builders.
type PromoCodeUsage func(*sql.Selector)

// RedeemCode is the predicate function for redeemcode builders.
type RedeemCode func(*sql.Selector)

// SecuritySecret is the predicate function for securitysecret builders.
type SecuritySecret func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// SubscriptionPlan is the predicate function for subscriptionplan builders.
type SubscriptionPlan func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAllowedGroup is the predicate function for userallowedgroup builders.
type UserAllowedGroup func(*sql.Selector)

// UserAttributeDefinition is the predicate function for userattributedefinition builders.
type UserAttributeDefinition func(*sql.Selector)

// UserAttributeValue is the predicate function for userattributevalue builders.
type UserAttributeValue func(*sql.Selector)

// UserSubscription is the predicate function for usersubscription builders.
type UserSubscription func(*sql.Selector)
