// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/meitianwang/fast-frame/ent"
	"github.com/meitianwang/fast-frame/internal/config"
	"github.com/meitianwang/fast-frame/internal/handler"
	"github.com/meitianwang/fast-frame/internal/handler/admin"
	"github.com/meitianwang/fast-frame/internal/repository"
	"github.com/meitianwang/fast-frame/internal/server"
	"github.com/meitianwang/fast-frame/internal/server/middleware"
	"github.com/meitianwang/fast-frame/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"net/http"
	"time"
)

import (
	_ "embed"
	_ "github.com/meitianwang/fast-frame/ent/runtime"
	_ "time/tzdata"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, configConfig)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := service.ProvideBillingCache()
	billingCacheService := service.NewBillingCacheService(billingCache)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator()
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	authService := service.NewAuthService(client, userRepository, redeemCodeRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, subscriptionService)
	userService := service.NewUserService(userRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService)
	userHandler := handler.NewUserHandler(userService)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.NewAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	dashboardHandler := admin.NewDashboardHandler()
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	adminService := service.NewAdminService(userRepository, groupRepository, redeemCodeRepository, userGroupRateRepository, settingService, subscriptionService, userSubscriptionRepository)
	adminUserHandler := admin.NewUserHandler(adminService)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	adminRedeemHandler := admin.NewRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	settingHandler := admin.NewSettingHandler(settingService, emailService, turnstileService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient()
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	paymentOrderRepository := repository.NewPaymentOrderRepository(client, db)
	paymentAuditLogRepository := repository.NewPaymentAuditLogRepository(client)
	paymentProviderInstanceRepository := repository.NewPaymentProviderInstanceRepository(client)
	subscriptionPlanRepository := repository.NewSubscriptionPlanRepository(client)
	paymentConfigService := service.NewPaymentConfigService(settingService)
	paymentProviderRegistry := service.NewPaymentProviderRegistry()
	paymentLoadBalancer := service.NewPaymentLoadBalancer(paymentProviderInstanceRepository, paymentOrderRepository, paymentConfigService, secretEncryptor)
	paymentOrderService := service.NewPaymentOrderService(paymentOrderRepository, paymentAuditLogRepository, paymentProviderInstanceRepository, subscriptionPlanRepository, groupRepository, userRepository, userService, paymentConfigService, paymentProviderRegistry, paymentLoadBalancer, secretEncryptor, client, redeemService, subscriptionService)
	paymentOrderHandler := admin.NewPaymentOrderHandler(paymentOrderService)
	paymentRefundHandler := admin.NewPaymentRefundHandler(paymentOrderService)
	paymentConfigHandler := admin.NewPaymentConfigHandler(paymentConfigService)
	paymentProviderInstanceHandler := admin.NewPaymentProviderInstanceHandler(paymentProviderInstanceRepository, secretEncryptor, paymentOrderService)
	paymentChannelRepository := repository.NewPaymentChannelRepository(client)
	paymentChannelHandler := admin.NewPaymentChannelHandler(paymentChannelRepository)
	paymentSubscriptionPlanHandler := admin.NewPaymentSubscriptionPlanHandler(subscriptionPlanRepository, paymentOrderService)
	paymentDashboardHandler := admin.NewPaymentDashboardHandler(paymentOrderService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, adminAnnouncementHandler, backupHandler, adminRedeemHandler, promoHandler, settingHandler, systemHandler, adminSubscriptionHandler, userAttributeHandler, paymentOrderHandler, paymentRefundHandler, paymentConfigHandler, paymentProviderInstanceHandler, paymentChannelHandler, paymentSubscriptionPlanHandler, paymentDashboardHandler)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo)
	totpHandler := handler.NewTotpHandler(totpService)
	paymentHandler := handler.NewPaymentHandler(paymentOrderService, paymentConfigService, paymentLoadBalancer, paymentChannelRepository, subscriptionPlanRepository)
	paymentWebhookHandler := handler.NewPaymentWebhookHandler(paymentOrderService)
	handlers := handler.ProvideHandlers(authHandler, userHandler, redeemHandler, subscriptionHandler, announcementHandler, adminHandlers, handlerSettingHandler, totpHandler, paymentHandler, paymentWebhookHandler)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, settingService, redisClient)
	httpServer := server.ProvideHTTPServer(configConfig, engine)
	subscriptionExpiryService := service.ProvideSubscriptionExpiryService(userSubscriptionRepository)
	paymentOrderExpiryService := service.ProvidePaymentOrderExpiryService(paymentOrderRepository, paymentAuditLogRepository, paymentProviderRegistry, paymentProviderInstanceRepository, secretEncryptor)
	v := provideCleanup(client, redisClient, subscriptionExpiryService, emailQueueService, subscriptionService, backupService, paymentOrderExpiryService)
	application := &Application{
		Server:  httpServer,
		Cleanup: v,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server  *http.Server
	Cleanup func()
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	subscriptionExpiry *service.SubscriptionExpiryService,
	emailQueue *service.EmailQueueService,
	subscriptionService *service.SubscriptionService,
	backupSvc *service.BackupService,
	paymentOrderExpiry *service.PaymentOrderExpiryService,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		if subscriptionExpiry != nil {
			subscriptionExpiry.Stop()
			log.Println("[Cleanup] SubscriptionExpiryService stopped")
		}
		if subscriptionService != nil {
			subscriptionService.Stop()
			log.Println("[Cleanup] SubscriptionService stopped")
		}
		if emailQueue != nil {
			emailQueue.Stop()
			log.Println("[Cleanup] EmailQueueService stopped")
		}
		if backupSvc != nil {
			backupSvc.Stop()
			log.Println("[Cleanup] BackupService stopped")
		}
		if paymentOrderExpiry != nil {
			paymentOrderExpiry.Stop()
			log.Println("[Cleanup] PaymentOrderExpiryService stopped")
		}

		if rdb != nil {
			if err := rdb.Close(); err != nil {
				log.Printf("[Cleanup] Redis close failed: %v", err)
			} else {
				log.Println("[Cleanup] Redis closed")
			}
		}
		if entClient != nil {
			if err := entClient.Close(); err != nil {
				log.Printf("[Cleanup] Ent close failed: %v", err)
			} else {
				log.Println("[Cleanup] Ent closed")
			}
		}

		select {
		case <-ctx.Done():
			log.Println("[Cleanup] Warning: cleanup timed out after 10 seconds")
		default:
			log.Println("[Cleanup] All cleanup steps completed")
		}
	}
}
