// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/meitianwang/fast-frame/ent/group"
)

// Group is the model entity for the Group schema.
type Group struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// IsExclusive holds the value of the "is_exclusive" field.
	IsExclusive bool `json:"is_exclusive,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SubscriptionType holds the value of the "subscription_type" field.
	SubscriptionType string `json:"subscription_type,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd *float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// DefaultValidityDays holds the value of the "default_validity_days" field.
	DefaultValidityDays int `json:"default_validity_days,omitempty"`
	// 分组显示排序，数值越小越靠前
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupQuery when eager-loading is set.
	Edges        GroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupEdges holds the relations/edges for other nodes in the graph.
type GroupEdges struct {
	// RedeemCodes holds the value of the redeem_codes edge.
	RedeemCodes []*RedeemCode `json:"redeem_codes,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*UserSubscription `json:"subscriptions,omitempty"`
	// AllowedUsers holds the value of the allowed_users edge.
	AllowedUsers []*User `json:"allowed_users,omitempty"`
	// SubscriptionPlans holds the value of the subscription_plans edge.
	SubscriptionPlans []*SubscriptionPlan `json:"subscription_plans,omitempty"`
	// PaymentChannels holds the value of the payment_channels edge.
	PaymentChannels []*PaymentChannel `json:"payment_channels,omitempty"`
	// UserAllowedGroups holds the value of the user_allowed_groups edge.
	UserAllowedGroups []*UserAllowedGroup `json:"user_allowed_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// RedeemCodesOrErr returns the RedeemCodes value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) RedeemCodesOrErr() ([]*RedeemCode, error) {
	if e.loadedTypes[0] {
		return e.RedeemCodes, nil
	}
	return nil, &NotLoadedError{edge: "redeem_codes"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) SubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[1] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// AllowedUsersOrErr returns the AllowedUsers value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) AllowedUsersOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.AllowedUsers, nil
	}
	return nil, &NotLoadedError{edge: "allowed_users"}
}

// SubscriptionPlansOrErr returns the SubscriptionPlans value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) SubscriptionPlansOrErr() ([]*SubscriptionPlan, error) {
	if e.loadedTypes[3] {
		return e.SubscriptionPlans, nil
	}
	return nil, &NotLoadedError{edge: "subscription_plans"}
}

// PaymentChannelsOrErr returns the PaymentChannels value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) PaymentChannelsOrErr() ([]*PaymentChannel, error) {
	if e.loadedTypes[4] {
		return e.PaymentChannels, nil
	}
	return nil, &NotLoadedError{edge: "payment_channels"}
}

// UserAllowedGroupsOrErr returns the UserAllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) UserAllowedGroupsOrErr() ([]*UserAllowedGroup, error) {
	if e.loadedTypes[5] {
		return e.UserAllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "user_allowed_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Group) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case group.FieldIsExclusive:
			values[i] = new(sql.NullBool)
		case group.FieldRateMultiplier, group.FieldDailyLimitUsd, group.FieldWeeklyLimitUsd, group.FieldMonthlyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case group.FieldID, group.FieldDefaultValidityDays, group.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case group.FieldName, group.FieldDescription, group.FieldStatus, group.FieldSubscriptionType:
			values[i] = new(sql.NullString)
		case group.FieldCreatedAt, group.FieldUpdatedAt, group.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Group fields.
func (_m *Group) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case group.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case group.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case group.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case group.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case group.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case group.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case group.FieldIsExclusive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_exclusive", values[i])
			} else if value.Valid {
				_m.IsExclusive = value.Bool
			}
		case group.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case group.FieldSubscriptionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_type", values[i])
			} else if value.Valid {
				_m.SubscriptionType = value.String
			}
		case group.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case group.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = new(float64)
				*_m.WeeklyLimitUsd = value.Float64
			}
		case group.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		case group.FieldDefaultValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_validity_days", values[i])
			} else if value.Valid {
				_m.DefaultValidityDays = int(value.Int64)
			}
		case group.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Group.
// This includes values selected through modifiers, order, etc.
func (_m *Group) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRedeemCodes queries the "redeem_codes" edge of the Group entity.
func (_m *Group) QueryRedeemCodes() *RedeemCodeQuery {
	return NewGroupClient(_m.config).QueryRedeemCodes(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the Group entity.
func (_m *Group) QuerySubscriptions() *UserSubscriptionQuery {
	return NewGroupClient(_m.config).QuerySubscriptions(_m)
}

// QueryAllowedUsers queries the "allowed_users" edge of the Group entity.
func (_m *Group) QueryAllowedUsers() *UserQuery {
	return NewGroupClient(_m.config).QueryAllowedUsers(_m)
}

// QuerySubscriptionPlans queries the "subscription_plans" edge of the Group entity.
func (_m *Group) QuerySubscriptionPlans() *SubscriptionPlanQuery {
	return NewGroupClient(_m.config).QuerySubscriptionPlans(_m)
}

// QueryPaymentChannels queries the "payment_channels" edge of the Group entity.
func (_m *Group) QueryPaymentChannels() *PaymentChannelQuery {
	return NewGroupClient(_m.config).QueryPaymentChannels(_m)
}

// QueryUserAllowedGroups queries the "user_allowed_groups" edge of the Group entity.
func (_m *Group) QueryUserAllowedGroups() *UserAllowedGroupQuery {
	return NewGroupClient(_m.config).QueryUserAllowedGroups(_m)
}

// Update returns a builder for updating this Group.
// Note that you need to call Group.Unwrap() before calling this method if this Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Group) Update() *GroupUpdateOne {
	return NewGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Group) Unwrap() *Group {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Group is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Group) String() string {
	var builder strings.Builder
	builder.WriteString("Group(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("is_exclusive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsExclusive))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("subscription_type=")
	builder.WriteString(_m.SubscriptionType)
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyLimitUsd; v != nil {
		builder.WriteString("weekly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("default_validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultValidityDays))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// Groups is a parsable slice of Group.
type Groups []*Group
