// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "content", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "draft"},
		{Name: "notify_mode", Type: field.TypeString, Size: 20, Default: "silent"},
		{Name: "targeting", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "starts_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "ends_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "announcement_status",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[3]},
			},
			{
				Name:    "announcement_created_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[10]},
			},
			{
				Name:    "announcement_starts_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[6]},
			},
			{
				Name:    "announcement_ends_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[7]},
			},
		},
	}
	// AnnouncementReadsColumns holds the columns for the "announcement_reads" table.
	AnnouncementReadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "read_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "announcement_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// AnnouncementReadsTable holds the schema information for the "announcement_reads" table.
	AnnouncementReadsTable = &schema.Table{
		Name:       "announcement_reads",
		Columns:    AnnouncementReadsColumns,
		PrimaryKey: []*schema.Column{AnnouncementReadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "announcement_reads_announcements_reads",
				Columns:    []*schema.Column{AnnouncementReadsColumns[3]},
				RefColumns: []*schema.Column{AnnouncementsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "announcement_reads_users_announcement_reads",
				Columns:    []*schema.Column{AnnouncementReadsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "announcementread_announcement_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[3]},
			},
			{
				Name:    "announcementread_user_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[4]},
			},
			{
				Name:    "announcementread_read_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[1]},
			},
			{
				Name:    "announcementread_announcement_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{AnnouncementReadsColumns[3], AnnouncementReadsColumns[4]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "is_exclusive", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "subscription_type", Type: field.TypeString, Size: 20, Default: "standard"},
		{Name: "daily_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "weekly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "monthly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "default_validity_days", Type: field.TypeInt, Default: 30},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "group_status",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[8]},
			},
			{
				Name:    "group_subscription_type",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[9]},
			},
			{
				Name:    "group_is_exclusive",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[7]},
			},
			{
				Name:    "group_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[3]},
			},
			{
				Name:    "group_sort_order",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[14]},
			},
		},
	}
	// IdempotencyRecordsColumns holds the columns for the "idempotency_records" table.
	IdempotencyRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "scope", Type: field.TypeString, Size: 128},
		{Name: "idempotency_key_hash", Type: field.TypeString, Size: 64},
		{Name: "request_fingerprint", Type: field.TypeString, Size: 64},
		{Name: "status", Type: field.TypeString, Size: 32},
		{Name: "response_status", Type: field.TypeInt, Nullable: true},
		{Name: "response_body", Type: field.TypeString, Nullable: true},
		{Name: "error_reason", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// IdempotencyRecordsTable holds the schema information for the "idempotency_records" table.
	IdempotencyRecordsTable = &schema.Table{
		Name:       "idempotency_records",
		Columns:    IdempotencyRecordsColumns,
		PrimaryKey: []*schema.Column{IdempotencyRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idempotencyrecord_scope_idempotency_key_hash",
				Unique:  true,
				Columns: []*schema.Column{IdempotencyRecordsColumns[3], IdempotencyRecordsColumns[4]},
			},
			{
				Name:    "idempotencyrecord_expires_at",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyRecordsColumns[11]},
			},
			{
				Name:    "idempotencyrecord_status_locked_until",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyRecordsColumns[6], IdempotencyRecordsColumns[10]},
			},
		},
	}
	// PaymentAuditLogsColumns holds the columns for the "payment_audit_logs" table.
	PaymentAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "action", Type: field.TypeString, Size: 50},
		{Name: "detail", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "operator", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "order_id", Type: field.TypeInt64},
	}
	// PaymentAuditLogsTable holds the schema information for the "payment_audit_logs" table.
	PaymentAuditLogsTable = &schema.Table{
		Name:       "payment_audit_logs",
		Columns:    PaymentAuditLogsColumns,
		PrimaryKey: []*schema.Column{PaymentAuditLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payment_audit_logs_payment_orders_audit_logs",
				Columns:    []*schema.Column{PaymentAuditLogsColumns[6]},
				RefColumns: []*schema.Column{PaymentOrdersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "paymentauditlog_order_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[6]},
			},
			{
				Name:    "paymentauditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[1]},
			},
		},
	}
	// PaymentChannelsColumns holds the columns for the "payment_channels" table.
	PaymentChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "platform", Type: field.TypeString, Size: 50, Default: "claude"},
		{Name: "rate_multiplier", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "models", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "features", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
	}
	// PaymentChannelsTable holds the schema information for the "payment_channels" table.
	PaymentChannelsTable = &schema.Table{
		Name:       "payment_channels",
		Columns:    PaymentChannelsColumns,
		PrimaryKey: []*schema.Column{PaymentChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payment_channels_groups_payment_channels",
				Columns:    []*schema.Column{PaymentChannelsColumns[11]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "paymentchannel_sort_order",
				Unique:  false,
				Columns: []*schema.Column{PaymentChannelsColumns[9]},
			},
		},
	}
	// PaymentOrdersColumns holds the columns for the "payment_orders" table.
	PaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_email", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "user_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "user_notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "amount", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "pay_amount", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "fee_rate", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(5,4)"}},
		{Name: "recharge_code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "payment_type", Type: field.TypeString, Size: 30},
		{Name: "payment_trade_no", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pay_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "qr_code", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "qr_code_img", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_amount", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "refund_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "force_refund", Type: field.TypeBool, Default: false},
		{Name: "refund_requested_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "refund_request_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_requested_by", Type: field.TypeInt64, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "failed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "failed_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "client_ip", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "src_host", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "src_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "order_type", Type: field.TypeString, Size: 20, Default: "balance"},
		{Name: "subscription_group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "subscription_days", Type: field.TypeInt, Nullable: true},
		{Name: "provider_instance_id", Type: field.TypeInt64, Nullable: true},
		{Name: "plan_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// PaymentOrdersTable holds the schema information for the "payment_orders" table.
	PaymentOrdersTable = &schema.Table{
		Name:       "payment_orders",
		Columns:    PaymentOrdersColumns,
		PrimaryKey: []*schema.Column{PaymentOrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payment_orders_payment_provider_instances_orders",
				Columns:    []*schema.Column{PaymentOrdersColumns[34]},
				RefColumns: []*schema.Column{PaymentProviderInstancesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "payment_orders_subscription_plans_orders",
				Columns:    []*schema.Column{PaymentOrdersColumns[35]},
				RefColumns: []*schema.Column{SubscriptionPlansColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "payment_orders_users_payment_orders",
				Columns:    []*schema.Column{PaymentOrdersColumns[36]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "paymentorder_user_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[36]},
			},
			{
				Name:    "paymentorder_status",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[10]},
			},
			{
				Name:    "paymentorder_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[23]},
			},
			{
				Name:    "paymentorder_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[1]},
			},
			{
				Name:    "paymentorder_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[24]},
			},
			{
				Name:    "paymentorder_payment_type_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[11], PaymentOrdersColumns[24]},
			},
			{
				Name:    "paymentorder_order_type",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[31]},
			},
			{
				Name:    "paymentorder_provider_instance_id_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[34], PaymentOrdersColumns[24]},
			},
		},
	}
	// PaymentProviderInstancesColumns holds the columns for the "payment_provider_instances" table.
	PaymentProviderInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "provider_key", Type: field.TypeString, Size: 30},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "config", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "supported_types", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "limits", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_enabled", Type: field.TypeBool, Default: false},
	}
	// PaymentProviderInstancesTable holds the schema information for the "payment_provider_instances" table.
	PaymentProviderInstancesTable = &schema.Table{
		Name:       "payment_provider_instances",
		Columns:    PaymentProviderInstancesColumns,
		PrimaryKey: []*schema.Column{PaymentProviderInstancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentproviderinstance_provider_key",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[3]},
			},
			{
				Name:    "paymentproviderinstance_provider_key_enabled",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[3], PaymentProviderInstancesColumns[7]},
			},
		},
	}
	// PromoCodesColumns holds the columns for the "promo_codes" table.
	PromoCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "bonus_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "max_uses", Type: field.TypeInt, Default: 0},
		{Name: "used_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PromoCodesTable holds the schema information for the "promo_codes" table.
	PromoCodesTable = &schema.Table{
		Name:       "promo_codes",
		Columns:    PromoCodesColumns,
		PrimaryKey: []*schema.Column{PromoCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "promocode_status",
				Unique:  false,
				Columns: []*schema.Column{PromoCodesColumns[5]},
			},
			{
				Name:    "promocode_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PromoCodesColumns[6]},
			},
		},
	}
	// PromoCodeUsagesColumns holds the columns for the "promo_code_usages" table.
	PromoCodeUsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "bonus_amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "used_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "promo_code_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// PromoCodeUsagesTable holds the schema information for the "promo_code_usages" table.
	PromoCodeUsagesTable = &schema.Table{
		Name:       "promo_code_usages",
		Columns:    PromoCodeUsagesColumns,
		PrimaryKey: []*schema.Column{PromoCodeUsagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "promo_code_usages_promo_codes_usage_records",
				Columns:    []*schema.Column{PromoCodeUsagesColumns[3]},
				RefColumns: []*schema.Column{PromoCodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "promo_code_usages_users_promo_code_usages",
				Columns:    []*schema.Column{PromoCodeUsagesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "promocodeusage_promo_code_id",
				Unique:  false,
				Columns: []*schema.Column{PromoCodeUsagesColumns[3]},
			},
			{
				Name:    "promocodeusage_user_id",
				Unique:  false,
				Columns: []*schema.Column{PromoCodeUsagesColumns[4]},
			},
			{
				Name:    "promocodeusage_promo_code_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{PromoCodeUsagesColumns[3], PromoCodeUsagesColumns[4]},
			},
		},
	}
	// RedeemCodesColumns holds the columns for the "redeem_codes" table.
	RedeemCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "type", Type: field.TypeString, Size: 20, Default: "balance"},
		{Name: "value", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "unused"},
		{Name: "used_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "validity_days", Type: field.TypeInt, Default: 30},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "used_by", Type: field.TypeInt64, Nullable: true},
	}
	// RedeemCodesTable holds the schema information for the "redeem_codes" table.
	RedeemCodesTable = &schema.Table{
		Name:       "redeem_codes",
		Columns:    RedeemCodesColumns,
		PrimaryKey: []*schema.Column{RedeemCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "redeem_codes_groups_redeem_codes",
				Columns:    []*schema.Column{RedeemCodesColumns[9]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "redeem_codes_users_redeem_codes",
				Columns:    []*schema.Column{RedeemCodesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "redeemcode_status",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[4]},
			},
			{
				Name:    "redeemcode_used_by",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[10]},
			},
			{
				Name:    "redeemcode_group_id",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[9]},
			},
		},
	}
	// SecuritySecretsColumns holds the columns for the "security_secrets" table.
	SecuritySecretsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
	}
	// SecuritySecretsTable holds the schema information for the "security_secrets" table.
	SecuritySecretsTable = &schema.Table{
		Name:       "security_secrets",
		Columns:    SecuritySecretsColumns,
		PrimaryKey: []*schema.Column{SecuritySecretsColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "setting_group", Type: field.TypeString, Size: 50, Default: "general"},
		{Name: "label", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "setting_setting_group",
				Unique:  false,
				Columns: []*schema.Column{SettingsColumns[3]},
			},
		},
	}
	// SubscriptionPlansColumns holds the columns for the "subscription_plans" table.
	SubscriptionPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "price", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "original_price", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "validity_days", Type: field.TypeInt, Default: 30},
		{Name: "validity_unit", Type: field.TypeString, Size: 10, Default: "day"},
		{Name: "features", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "product_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "for_sale", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
	}
	// SubscriptionPlansTable holds the schema information for the "subscription_plans" table.
	SubscriptionPlansTable = &schema.Table{
		Name:       "subscription_plans",
		Columns:    SubscriptionPlansColumns,
		PrimaryKey: []*schema.Column{SubscriptionPlansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscription_plans_groups_subscription_plans",
				Columns:    []*schema.Column{SubscriptionPlansColumns[13]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "subscriptionplan_for_sale_sort_order",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[11], SubscriptionPlansColumns[12]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "concurrency", Type: field.TypeInt, Default: 5},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "username", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "notes", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "totp_secret_encrypted", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "totp_enabled", Type: field.TypeBool, Default: false},
		{Name: "totp_enabled_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[9]},
			},
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// UserAllowedGroupsColumns holds the columns for the "user_allowed_groups" table.
	UserAllowedGroupsColumns = []*schema.Column{
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64},
	}
	// UserAllowedGroupsTable holds the schema information for the "user_allowed_groups" table.
	UserAllowedGroupsTable = &schema.Table{
		Name:       "user_allowed_groups",
		Columns:    UserAllowedGroupsColumns,
		PrimaryKey: []*schema.Column{UserAllowedGroupsColumns[1], UserAllowedGroupsColumns[2]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_allowed_groups_users_user",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_allowed_groups_groups_group",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[2]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userallowedgroup_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserAllowedGroupsColumns[2]},
			},
		},
	}
	// UserAttributeDefinitionsColumns holds the columns for the "user_attribute_definitions" table.
	UserAttributeDefinitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "options", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "required", Type: field.TypeBool, Default: false},
		{Name: "validation", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "placeholder", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// UserAttributeDefinitionsTable holds the schema information for the "user_attribute_definitions" table.
	UserAttributeDefinitionsTable = &schema.Table{
		Name:       "user_attribute_definitions",
		Columns:    UserAttributeDefinitionsColumns,
		PrimaryKey: []*schema.Column{UserAttributeDefinitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userattributedefinition_key",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[4]},
			},
			{
				Name:    "userattributedefinition_enabled",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[13]},
			},
			{
				Name:    "userattributedefinition_display_order",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[12]},
			},
			{
				Name:    "userattributedefinition_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[3]},
			},
		},
	}
	// UserAttributeValuesColumns holds the columns for the "user_attribute_values" table.
	UserAttributeValuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "attribute_id", Type: field.TypeInt64},
	}
	// UserAttributeValuesTable holds the schema information for the "user_attribute_values" table.
	UserAttributeValuesTable = &schema.Table{
		Name:       "user_attribute_values",
		Columns:    UserAttributeValuesColumns,
		PrimaryKey: []*schema.Column{UserAttributeValuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_attribute_values_users_attribute_values",
				Columns:    []*schema.Column{UserAttributeValuesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_attribute_values_user_attribute_definitions_values",
				Columns:    []*schema.Column{UserAttributeValuesColumns[5]},
				RefColumns: []*schema.Column{UserAttributeDefinitionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userattributevalue_user_id_attribute_id",
				Unique:  true,
				Columns: []*schema.Column{UserAttributeValuesColumns[4], UserAttributeValuesColumns[5]},
			},
			{
				Name:    "userattributevalue_attribute_id",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeValuesColumns[5]},
			},
		},
	}
	// UserSubscriptionsColumns holds the columns for the "user_subscriptions" table.
	UserSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "starts_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "daily_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "weekly_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "monthly_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "daily_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "weekly_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "monthly_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "assigned_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "group_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "assigned_by", Type: field.TypeInt64, Nullable: true},
	}
	// UserSubscriptionsTable holds the schema information for the "user_subscriptions" table.
	UserSubscriptionsTable = &schema.Table{
		Name:       "user_subscriptions",
		Columns:    UserSubscriptionsColumns,
		PrimaryKey: []*schema.Column{UserSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_subscriptions_groups_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[15]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[16]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_assigned_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[17]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usersubscription_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[16]},
			},
			{
				Name:    "usersubscription_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[15]},
			},
			{
				Name:    "usersubscription_status",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[6]},
			},
			{
				Name:    "usersubscription_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[5]},
			},
			{
				Name:    "usersubscription_user_id_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[16], UserSubscriptionsColumns[6], UserSubscriptionsColumns[5]},
			},
			{
				Name:    "usersubscription_assigned_by",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[17]},
			},
			{
				Name:    "usersubscription_user_id_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[16], UserSubscriptionsColumns[15]},
			},
			{
				Name:    "usersubscription_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnnouncementsTable,
		AnnouncementReadsTable,
		GroupsTable,
		IdempotencyRecordsTable,
		PaymentAuditLogsTable,
		PaymentChannelsTable,
		PaymentOrdersTable,
		PaymentProviderInstancesTable,
		PromoCodesTable,
		PromoCodeUsagesTable,
		RedeemCodesTable,
		SecuritySecretsTable,
		SettingsTable,
		SubscriptionPlansTable,
		UsersTable,
		UserAllowedGroupsTable,
		UserAttributeDefinitionsTable,
		UserAttributeValuesTable,
		UserSubscriptionsTable,
	}
)

func init() {
	AnnouncementsTable.Annotation = &entsql.Annotation{
		Table: "announcements",
	}
	AnnouncementReadsTable.ForeignKeys[0].RefTable = AnnouncementsTable
	AnnouncementReadsTable.ForeignKeys[1].RefTable = UsersTable
	AnnouncementReadsTable.Annotation = &entsql.Annotation{
		Table: "announcement_reads",
	}
	GroupsTable.Annotation = &entsql.Annotation{
		Table: "groups",
	}
	IdempotencyRecordsTable.Annotation = &entsql.Annotation{
		Table: "idempotency_records",
	}
	PaymentAuditLogsTable.ForeignKeys[0].RefTable = PaymentOrdersTable
	PaymentAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "payment_audit_logs",
	}
	PaymentChannelsTable.ForeignKeys[0].RefTable = GroupsTable
	PaymentChannelsTable.Annotation = &entsql.Annotation{
		Table: "payment_channels",
	}
	PaymentOrdersTable.ForeignKeys[0].RefTable = PaymentProviderInstancesTable
	PaymentOrdersTable.ForeignKeys[1].RefTable = SubscriptionPlansTable
	PaymentOrdersTable.ForeignKeys[2].RefTable = UsersTable
	PaymentOrdersTable.Annotation = &entsql.Annotation{
		Table: "payment_orders",
	}
	PaymentProviderInstancesTable.Annotation = &entsql.Annotation{
		Table: "payment_provider_instances",
	}
	PromoCodesTable.Annotation = &entsql.Annotation{
		Table: "promo_codes",
	}
	PromoCodeUsagesTable.ForeignKeys[0].RefTable = PromoCodesTable
	PromoCodeUsagesTable.ForeignKeys[1].RefTable = UsersTable
	PromoCodeUsagesTable.Annotation = &entsql.Annotation{
		Table: "promo_code_usages",
	}
	RedeemCodesTable.ForeignKeys[0].RefTable = GroupsTable
	RedeemCodesTable.ForeignKeys[1].RefTable = UsersTable
	RedeemCodesTable.Annotation = &entsql.Annotation{
		Table: "redeem_codes",
	}
	SecuritySecretsTable.Annotation = &entsql.Annotation{
		Table: "security_secrets",
	}
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "settings",
	}
	SubscriptionPlansTable.ForeignKeys[0].RefTable = GroupsTable
	SubscriptionPlansTable.Annotation = &entsql.Annotation{
		Table: "subscription_plans",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	UserAllowedGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserAllowedGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	UserAllowedGroupsTable.Annotation = &entsql.Annotation{
		Table: "user_allowed_groups",
	}
	UserAttributeDefinitionsTable.Annotation = &entsql.Annotation{
		Table: "user_attribute_definitions",
	}
	UserAttributeValuesTable.ForeignKeys[0].RefTable = UsersTable
	UserAttributeValuesTable.ForeignKeys[1].RefTable = UserAttributeDefinitionsTable
	UserAttributeValuesTable.Annotation = &entsql.Annotation{
		Table: "user_attribute_values",
	}
	UserSubscriptionsTable.ForeignKeys[0].RefTable = GroupsTable
	UserSubscriptionsTable.ForeignKeys[1].RefTable = UsersTable
	UserSubscriptionsTable.ForeignKeys[2].RefTable = UsersTable
	UserSubscriptionsTable.Annotation = &entsql.Annotation{
		Table: "user_subscriptions",
	}
}
