// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/meitianwang/fast-frame/ent/announcement"
	"github.com/meitianwang/fast-frame/ent/announcementread"
	"github.com/meitianwang/fast-frame/ent/group"
	"github.com/meitianwang/fast-frame/ent/idempotencyrecord"
	"github.com/meitianwang/fast-frame/ent/paymentauditlog"
	"github.com/meitianwang/fast-frame/ent/paymentchannel"
	"github.com/meitianwang/fast-frame/ent/paymentorder"
	"github.com/meitianwang/fast-frame/ent/paymentproviderinstance"
	"github.com/meitianwang/fast-frame/ent/promocode"
	"github.com/meitianwang/fast-frame/ent/promocodeusage"
	"github.com/meitianwang/fast-frame/ent/redeemcode"
	"github.com/meitianwang/fast-frame/ent/schema"
	"github.com/meitianwang/fast-frame/ent/securitysecret"
	"github.com/meitianwang/fast-frame/ent/setting"
	"github.com/meitianwang/fast-frame/ent/subscriptionplan"
	"github.com/meitianwang/fast-frame/ent/user"
	"github.com/meitianwang/fast-frame/ent/userallowedgroup"
	"github.com/meitianwang/fast-frame/ent/userattributedefinition"
	"github.com/meitianwang/fast-frame/ent/userattributevalue"
	"github.com/meitianwang/fast-frame/ent/usersubscription"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	announcementFields := schema.Announcement{}.Fields()
	_ = announcementFields
	// announcementDescTitle is the schema descriptor for title field.
	announcementDescTitle := announcementFields[0].Descriptor()
	// announcement.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	announcement.TitleValidator = func() func(string) error {
		validators := announcementDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// announcementDescContent is the schema descriptor for content field.
	announcementDescContent := announcementFields[1].Descriptor()
	// announcement.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	announcement.ContentValidator = announcementDescContent.Validators[0].(func(string) error)
	// announcementDescStatus is the schema descriptor for status field.
	announcementDescStatus := announcementFields[2].Descriptor()
	// announcement.DefaultStatus holds the default value on creation for the status field.
	announcement.DefaultStatus = announcementDescStatus.Default.(string)
	// announcement.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	announcement.StatusValidator = announcementDescStatus.Validators[0].(func(string) error)
	// announcementDescNotifyMode is the schema descriptor for notify_mode field.
	announcementDescNotifyMode := announcementFields[3].Descriptor()
	// announcement.DefaultNotifyMode holds the default value on creation for the notify_mode field.
	announcement.DefaultNotifyMode = announcementDescNotifyMode.Default.(string)
	// announcement.NotifyModeValidator is a validator for the "notify_mode" field. It is called by the builders before save.
	announcement.NotifyModeValidator = announcementDescNotifyMode.Validators[0].(func(string) error)
	// announcementDescCreatedAt is the schema descriptor for created_at field.
	announcementDescCreatedAt := announcementFields[9].Descriptor()
	// announcement.DefaultCreatedAt holds the default value on creation for the created_at field.
	announcement.DefaultCreatedAt = announcementDescCreatedAt.Default.(func() time.Time)
	// announcementDescUpdatedAt is the schema descriptor for updated_at field.
	announcementDescUpdatedAt := announcementFields[10].Descriptor()
	// announcement.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	announcement.DefaultUpdatedAt = announcementDescUpdatedAt.Default.(func() time.Time)
	// announcement.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	announcement.UpdateDefaultUpdatedAt = announcementDescUpdatedAt.UpdateDefault.(func() time.Time)
	announcementreadFields := schema.AnnouncementRead{}.Fields()
	_ = announcementreadFields
	// announcementreadDescReadAt is the schema descriptor for read_at field.
	announcementreadDescReadAt := announcementreadFields[2].Descriptor()
	// announcementread.DefaultReadAt holds the default value on creation for the read_at field.
	announcementread.DefaultReadAt = announcementreadDescReadAt.Default.(func() time.Time)
	// announcementreadDescCreatedAt is the schema descriptor for created_at field.
	announcementreadDescCreatedAt := announcementreadFields[3].Descriptor()
	// announcementread.DefaultCreatedAt holds the default value on creation for the created_at field.
	announcementread.DefaultCreatedAt = announcementreadDescCreatedAt.Default.(func() time.Time)
	groupMixin := schema.Group{}.Mixin()
	groupMixinHooks1 := groupMixin[1].Hooks()
	group.Hooks[0] = groupMixinHooks1[0]
	groupMixinInters1 := groupMixin[1].Interceptors()
	group.Interceptors[0] = groupMixinInters1[0]
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescRateMultiplier is the schema descriptor for rate_multiplier field.
	groupDescRateMultiplier := groupFields[2].Descriptor()
	// group.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	group.DefaultRateMultiplier = groupDescRateMultiplier.Default.(float64)
	// groupDescIsExclusive is the schema descriptor for is_exclusive field.
	groupDescIsExclusive := groupFields[3].Descriptor()
	// group.DefaultIsExclusive holds the default value on creation for the is_exclusive field.
	group.DefaultIsExclusive = groupDescIsExclusive.Default.(bool)
	// groupDescStatus is the schema descriptor for status field.
	groupDescStatus := groupFields[4].Descriptor()
	// group.DefaultStatus holds the default value on creation for the status field.
	group.DefaultStatus = groupDescStatus.Default.(string)
	// group.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	group.StatusValidator = groupDescStatus.Validators[0].(func(string) error)
	// groupDescSubscriptionType is the schema descriptor for subscription_type field.
	groupDescSubscriptionType := groupFields[5].Descriptor()
	// group.DefaultSubscriptionType holds the default value on creation for the subscription_type field.
	group.DefaultSubscriptionType = groupDescSubscriptionType.Default.(string)
	// group.SubscriptionTypeValidator is a validator for the "subscription_type" field. It is called by the builders before save.
	group.SubscriptionTypeValidator = groupDescSubscriptionType.Validators[0].(func(string) error)
	// groupDescDefaultValidityDays is the schema descriptor for default_validity_days field.
	groupDescDefaultValidityDays := groupFields[9].Descriptor()
	// group.DefaultDefaultValidityDays holds the default value on creation for the default_validity_days field.
	group.DefaultDefaultValidityDays = groupDescDefaultValidityDays.Default.(int)
	// groupDescSortOrder is the schema descriptor for sort_order field.
	groupDescSortOrder := groupFields[10].Descriptor()
	// group.DefaultSortOrder holds the default value on creation for the sort_order field.
	group.DefaultSortOrder = groupDescSortOrder.Default.(int)
	idempotencyrecordMixin := schema.IdempotencyRecord{}.Mixin()
	idempotencyrecordMixinFields0 := idempotencyrecordMixin[0].Fields()
	_ = idempotencyrecordMixinFields0
	idempotencyrecordFields := schema.IdempotencyRecord{}.Fields()
	_ = idempotencyrecordFields
	// idempotencyrecordDescCreatedAt is the schema descriptor for created_at field.
	idempotencyrecordDescCreatedAt := idempotencyrecordMixinFields0[0].Descriptor()
	// idempotencyrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	idempotencyrecord.DefaultCreatedAt = idempotencyrecordDescCreatedAt.Default.(func() time.Time)
	// idempotencyrecordDescUpdatedAt is the schema descriptor for updated_at field.
	idempotencyrecordDescUpdatedAt := idempotencyrecordMixinFields0[1].Descriptor()
	// idempotencyrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	idempotencyrecord.DefaultUpdatedAt = idempotencyrecordDescUpdatedAt.Default.(func() time.Time)
	// idempotencyrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	idempotencyrecord.UpdateDefaultUpdatedAt = idempotencyrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// idempotencyrecordDescScope is the schema descriptor for scope field.
	idempotencyrecordDescScope := idempotencyrecordFields[0].Descriptor()
	// idempotencyrecord.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	idempotencyrecord.ScopeValidator = idempotencyrecordDescScope.Validators[0].(func(string) error)
	// idempotencyrecordDescIdempotencyKeyHash is the schema descriptor for idempotency_key_hash field.
	idempotencyrecordDescIdempotencyKeyHash := idempotencyrecordFields[1].Descriptor()
	// idempotencyrecord.IdempotencyKeyHashValidator is a validator for the "idempotency_key_hash" field. It is called by the builders before save.
	idempotencyrecord.IdempotencyKeyHashValidator = idempotencyrecordDescIdempotencyKeyHash.Validators[0].(func(string) error)
	// idempotencyrecordDescRequestFingerprint is the schema descriptor for request_fingerprint field.
	idempotencyrecordDescRequestFingerprint := idempotencyrecordFields[2].Descriptor()
	// idempotencyrecord.RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	idempotencyrecord.RequestFingerprintValidator = idempotencyrecordDescRequestFingerprint.Validators[0].(func(string) error)
	// idempotencyrecordDescStatus is the schema descriptor for status field.
	idempotencyrecordDescStatus := idempotencyrecordFields[3].Descriptor()
	// idempotencyrecord.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	idempotencyrecord.StatusValidator = idempotencyrecordDescStatus.Validators[0].(func(string) error)
	// idempotencyrecordDescErrorReason is the schema descriptor for error_reason field.
	idempotencyrecordDescErrorReason := idempotencyrecordFields[6].Descriptor()
	// idempotencyrecord.ErrorReasonValidator is a validator for the "error_reason" field. It is called by the builders before save.
	idempotencyrecord.ErrorReasonValidator = idempotencyrecordDescErrorReason.Validators[0].(func(string) error)
	paymentauditlogMixin := schema.PaymentAuditLog{}.Mixin()
	paymentauditlogMixinFields0 := paymentauditlogMixin[0].Fields()
	_ = paymentauditlogMixinFields0
	paymentauditlogFields := schema.PaymentAuditLog{}.Fields()
	_ = paymentauditlogFields
	// paymentauditlogDescCreatedAt is the schema descriptor for created_at field.
	paymentauditlogDescCreatedAt := paymentauditlogMixinFields0[0].Descriptor()
	// paymentauditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentauditlog.DefaultCreatedAt = paymentauditlogDescCreatedAt.Default.(func() time.Time)
	// paymentauditlogDescUpdatedAt is the schema descriptor for updated_at field.
	paymentauditlogDescUpdatedAt := paymentauditlogMixinFields0[1].Descriptor()
	// paymentauditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentauditlog.DefaultUpdatedAt = paymentauditlogDescUpdatedAt.Default.(func() time.Time)
	// paymentauditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentauditlog.UpdateDefaultUpdatedAt = paymentauditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentauditlogDescAction is the schema descriptor for action field.
	paymentauditlogDescAction := paymentauditlogFields[1].Descriptor()
	// paymentauditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	paymentauditlog.ActionValidator = func() func(string) error {
		validators := paymentauditlogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentauditlogDescOperator is the schema descriptor for operator field.
	paymentauditlogDescOperator := paymentauditlogFields[3].Descriptor()
	// paymentauditlog.OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	paymentauditlog.OperatorValidator = paymentauditlogDescOperator.Validators[0].(func(string) error)
	paymentchannelMixin := schema.PaymentChannel{}.Mixin()
	paymentchannelMixinFields0 := paymentchannelMixin[0].Fields()
	_ = paymentchannelMixinFields0
	paymentchannelFields := schema.PaymentChannel{}.Fields()
	_ = paymentchannelFields
	// paymentchannelDescCreatedAt is the schema descriptor for created_at field.
	paymentchannelDescCreatedAt := paymentchannelMixinFields0[0].Descriptor()
	// paymentchannel.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentchannel.DefaultCreatedAt = paymentchannelDescCreatedAt.Default.(func() time.Time)
	// paymentchannelDescUpdatedAt is the schema descriptor for updated_at field.
	paymentchannelDescUpdatedAt := paymentchannelMixinFields0[1].Descriptor()
	// paymentchannel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentchannel.DefaultUpdatedAt = paymentchannelDescUpdatedAt.Default.(func() time.Time)
	// paymentchannel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentchannel.UpdateDefaultUpdatedAt = paymentchannelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentchannelDescName is the schema descriptor for name field.
	paymentchannelDescName := paymentchannelFields[1].Descriptor()
	// paymentchannel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	paymentchannel.NameValidator = func() func(string) error {
		validators := paymentchannelDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentchannelDescPlatform is the schema descriptor for platform field.
	paymentchannelDescPlatform := paymentchannelFields[2].Descriptor()
	// paymentchannel.DefaultPlatform holds the default value on creation for the platform field.
	paymentchannel.DefaultPlatform = paymentchannelDescPlatform.Default.(string)
	// paymentchannel.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	paymentchannel.PlatformValidator = paymentchannelDescPlatform.Validators[0].(func(string) error)
	// paymentchannelDescSortOrder is the schema descriptor for sort_order field.
	paymentchannelDescSortOrder := paymentchannelFields[7].Descriptor()
	// paymentchannel.DefaultSortOrder holds the default value on creation for the sort_order field.
	paymentchannel.DefaultSortOrder = paymentchannelDescSortOrder.Default.(int)
	// paymentchannelDescEnabled is the schema descriptor for enabled field.
	paymentchannelDescEnabled := paymentchannelFields[8].Descriptor()
	// paymentchannel.DefaultEnabled holds the default value on creation for the enabled field.
	paymentchannel.DefaultEnabled = paymentchannelDescEnabled.Default.(bool)
	paymentorderMixin := schema.PaymentOrder{}.Mixin()
	paymentorderMixinFields0 := paymentorderMixin[0].Fields()
	_ = paymentorderMixinFields0
	paymentorderFields := schema.PaymentOrder{}.Fields()
	_ = paymentorderFields
	// paymentorderDescCreatedAt is the schema descriptor for created_at field.
	paymentorderDescCreatedAt := paymentorderMixinFields0[0].Descriptor()
	// paymentorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentorder.DefaultCreatedAt = paymentorderDescCreatedAt.Default.(func() time.Time)
	// paymentorderDescUpdatedAt is the schema descriptor for updated_at field.
	paymentorderDescUpdatedAt := paymentorderMixinFields0[1].Descriptor()
	// paymentorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentorder.DefaultUpdatedAt = paymentorderDescUpdatedAt.Default.(func() time.Time)
	// paymentorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentorder.UpdateDefaultUpdatedAt = paymentorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentorderDescUserEmail is the schema descriptor for user_email field.
	paymentorderDescUserEmail := paymentorderFields[1].Descriptor()
	// paymentorder.UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	paymentorder.UserEmailValidator = paymentorderDescUserEmail.Validators[0].(func(string) error)
	// paymentorderDescUserName is the schema descriptor for user_name field.
	paymentorderDescUserName := paymentorderFields[2].Descriptor()
	// paymentorder.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	paymentorder.UserNameValidator = paymentorderDescUserName.Validators[0].(func(string) error)
	// paymentorderDescRechargeCode is the schema descriptor for recharge_code field.
	paymentorderDescRechargeCode := paymentorderFields[7].Descriptor()
	// paymentorder.RechargeCodeValidator is a validator for the "recharge_code" field. It is called by the builders before save.
	paymentorder.RechargeCodeValidator = func() func(string) error {
		validators := paymentorderDescRechargeCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(recharge_code string) error {
			for _, fn := range fns {
				if err := fn(recharge_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentorderDescStatus is the schema descriptor for status field.
	paymentorderDescStatus := paymentorderFields[8].Descriptor()
	// paymentorder.DefaultStatus holds the default value on creation for the status field.
	paymentorder.DefaultStatus = paymentorderDescStatus.Default.(string)
	// paymentorder.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	paymentorder.StatusValidator = paymentorderDescStatus.Validators[0].(func(string) error)
	// paymentorderDescPaymentType is the schema descriptor for payment_type field.
	paymentorderDescPaymentType := paymentorderFields[9].Descriptor()
	// paymentorder.PaymentTypeValidator is a validator for the "payment_type" field. It is called by the builders before save.
	paymentorder.PaymentTypeValidator = func() func(string) error {
		validators := paymentorderDescPaymentType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(payment_type string) error {
			for _, fn := range fns {
				if err := fn(payment_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentorderDescPaymentTradeNo is the schema descriptor for payment_trade_no field.
	paymentorderDescPaymentTradeNo := paymentorderFields[10].Descriptor()
	// paymentorder.PaymentTradeNoValidator is a validator for the "payment_trade_no" field. It is called by the builders before save.
	paymentorder.PaymentTradeNoValidator = paymentorderDescPaymentTradeNo.Validators[0].(func(string) error)
	// paymentorderDescForceRefund is the schema descriptor for force_refund field.
	paymentorderDescForceRefund := paymentorderFields[17].Descriptor()
	// paymentorder.DefaultForceRefund holds the default value on creation for the force_refund field.
	paymentorder.DefaultForceRefund = paymentorderDescForceRefund.Default.(bool)
	// paymentorderDescClientIP is the schema descriptor for client_ip field.
	paymentorderDescClientIP := paymentorderFields[26].Descriptor()
	// paymentorder.ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	paymentorder.ClientIPValidator = paymentorderDescClientIP.Validators[0].(func(string) error)
	// paymentorderDescSrcHost is the schema descriptor for src_host field.
	paymentorderDescSrcHost := paymentorderFields[27].Descriptor()
	// paymentorder.SrcHostValidator is a validator for the "src_host" field. It is called by the builders before save.
	paymentorder.SrcHostValidator = paymentorderDescSrcHost.Validators[0].(func(string) error)
	// paymentorderDescOrderType is the schema descriptor for order_type field.
	paymentorderDescOrderType := paymentorderFields[29].Descriptor()
	// paymentorder.DefaultOrderType holds the default value on creation for the order_type field.
	paymentorder.DefaultOrderType = paymentorderDescOrderType.Default.(string)
	// paymentorder.OrderTypeValidator is a validator for the "order_type" field. It is called by the builders before save.
	paymentorder.OrderTypeValidator = paymentorderDescOrderType.Validators[0].(func(string) error)
	paymentproviderinstanceMixin := schema.PaymentProviderInstance{}.Mixin()
	paymentproviderinstanceMixinFields0 := paymentproviderinstanceMixin[0].Fields()
	_ = paymentproviderinstanceMixinFields0
	paymentproviderinstanceFields := schema.PaymentProviderInstance{}.Fields()
	_ = paymentproviderinstanceFields
	// paymentproviderinstanceDescCreatedAt is the schema descriptor for created_at field.
	paymentproviderinstanceDescCreatedAt := paymentproviderinstanceMixinFields0[0].Descriptor()
	// paymentproviderinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentproviderinstance.DefaultCreatedAt = paymentproviderinstanceDescCreatedAt.Default.(func() time.Time)
	// paymentproviderinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	paymentproviderinstanceDescUpdatedAt := paymentproviderinstanceMixinFields0[1].Descriptor()
	// paymentproviderinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentproviderinstance.DefaultUpdatedAt = paymentproviderinstanceDescUpdatedAt.Default.(func() time.Time)
	// paymentproviderinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentproviderinstance.UpdateDefaultUpdatedAt = paymentproviderinstanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentproviderinstanceDescProviderKey is the schema descriptor for provider_key field.
	paymentproviderinstanceDescProviderKey := paymentproviderinstanceFields[0].Descriptor()
	// paymentproviderinstance.ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	paymentproviderinstance.ProviderKeyValidator = func() func(string) error {
		validators := paymentproviderinstanceDescProviderKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider_key string) error {
			for _, fn := range fns {
				if err := fn(provider_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentproviderinstanceDescName is the schema descriptor for name field.
	paymentproviderinstanceDescName := paymentproviderinstanceFields[1].Descriptor()
	// paymentproviderinstance.NameValidator is a validator for the "name" field. It is called by the builders before save.
	paymentproviderinstance.NameValidator = func() func(string) error {
		validators := paymentproviderinstanceDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentproviderinstanceDescConfig is the schema descriptor for config field.
	paymentproviderinstanceDescConfig := paymentproviderinstanceFields[2].Descriptor()
	// paymentproviderinstance.ConfigValidator is a validator for the "config" field. It is called by the builders before save.
	paymentproviderinstance.ConfigValidator = paymentproviderinstanceDescConfig.Validators[0].(func(string) error)
	// paymentproviderinstanceDescSupportedTypes is the schema descriptor for supported_types field.
	paymentproviderinstanceDescSupportedTypes := paymentproviderinstanceFields[3].Descriptor()
	// paymentproviderinstance.DefaultSupportedTypes holds the default value on creation for the supported_types field.
	paymentproviderinstance.DefaultSupportedTypes = paymentproviderinstanceDescSupportedTypes.Default.(string)
	// paymentproviderinstance.SupportedTypesValidator is a validator for the "supported_types" field. It is called by the builders before save.
	paymentproviderinstance.SupportedTypesValidator = paymentproviderinstanceDescSupportedTypes.Validators[0].(func(string) error)
	// paymentproviderinstanceDescEnabled is the schema descriptor for enabled field.
	paymentproviderinstanceDescEnabled := paymentproviderinstanceFields[4].Descriptor()
	// paymentproviderinstance.DefaultEnabled holds the default value on creation for the enabled field.
	paymentproviderinstance.DefaultEnabled = paymentproviderinstanceDescEnabled.Default.(bool)
	// paymentproviderinstanceDescSortOrder is the schema descriptor for sort_order field.
	paymentproviderinstanceDescSortOrder := paymentproviderinstanceFields[5].Descriptor()
	// paymentproviderinstance.DefaultSortOrder holds the default value on creation for the sort_order field.
	paymentproviderinstance.DefaultSortOrder = paymentproviderinstanceDescSortOrder.Default.(int)
	// paymentproviderinstanceDescRefundEnabled is the schema descriptor for refund_enabled field.
	paymentproviderinstanceDescRefundEnabled := paymentproviderinstanceFields[7].Descriptor()
	// paymentproviderinstance.DefaultRefundEnabled holds the default value on creation for the refund_enabled field.
	paymentproviderinstance.DefaultRefundEnabled = paymentproviderinstanceDescRefundEnabled.Default.(bool)
	promocodeFields := schema.PromoCode{}.Fields()
	_ = promocodeFields
	// promocodeDescCode is the schema descriptor for code field.
	promocodeDescCode := promocodeFields[0].Descriptor()
	// promocode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	promocode.CodeValidator = func() func(string) error {
		validators := promocodeDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// promocodeDescBonusAmount is the schema descriptor for bonus_amount field.
	promocodeDescBonusAmount := promocodeFields[1].Descriptor()
	// promocode.DefaultBonusAmount holds the default value on creation for the bonus_amount field.
	promocode.DefaultBonusAmount = promocodeDescBonusAmount.Default.(float64)
	// promocodeDescMaxUses is the schema descriptor for max_uses field.
	promocodeDescMaxUses := promocodeFields[2].Descriptor()
	// promocode.DefaultMaxUses holds the default value on creation for the max_uses field.
	promocode.DefaultMaxUses = promocodeDescMaxUses.Default.(int)
	// promocodeDescUsedCount is the schema descriptor for used_count field.
	promocodeDescUsedCount := promocodeFields[3].Descriptor()
	// promocode.DefaultUsedCount holds the default value on creation for the used_count field.
	promocode.DefaultUsedCount = promocodeDescUsedCount.Default.(int)
	// promocodeDescStatus is the schema descriptor for status field.
	promocodeDescStatus := promocodeFields[4].Descriptor()
	// promocode.DefaultStatus holds the default value on creation for the status field.
	promocode.DefaultStatus = promocodeDescStatus.Default.(string)
	// promocode.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	promocode.StatusValidator = promocodeDescStatus.Validators[0].(func(string) error)
	// promocodeDescCreatedAt is the schema descriptor for created_at field.
	promocodeDescCreatedAt := promocodeFields[7].Descriptor()
	// promocode.DefaultCreatedAt holds the default value on creation for the created_at field.
	promocode.DefaultCreatedAt = promocodeDescCreatedAt.Default.(func() time.Time)
	// promocodeDescUpdatedAt is the schema descriptor for updated_at field.
	promocodeDescUpdatedAt := promocodeFields[8].Descriptor()
	// promocode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	promocode.DefaultUpdatedAt = promocodeDescUpdatedAt.Default.(func() time.Time)
	// promocode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	promocode.UpdateDefaultUpdatedAt = promocodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	promocodeusageFields := schema.PromoCodeUsage{}.Fields()
	_ = promocodeusageFields
	// promocodeusageDescUsedAt is the schema descriptor for used_at field.
	promocodeusageDescUsedAt := promocodeusageFields[3].Descriptor()
	// promocodeusage.DefaultUsedAt holds the default value on creation for the used_at field.
	promocodeusage.DefaultUsedAt = promocodeusageDescUsedAt.Default.(func() time.Time)
	redeemcodeFields := schema.RedeemCode{}.Fields()
	_ = redeemcodeFields
	// redeemcodeDescCode is the schema descriptor for code field.
	redeemcodeDescCode := redeemcodeFields[0].Descriptor()
	// redeemcode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	redeemcode.CodeValidator = func() func(string) error {
		validators := redeemcodeDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// redeemcodeDescType is the schema descriptor for type field.
	redeemcodeDescType := redeemcodeFields[1].Descriptor()
	// redeemcode.DefaultType holds the default value on creation for the type field.
	redeemcode.DefaultType = redeemcodeDescType.Default.(string)
	// redeemcode.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	redeemcode.TypeValidator = redeemcodeDescType.Validators[0].(func(string) error)
	// redeemcodeDescValue is the schema descriptor for value field.
	redeemcodeDescValue := redeemcodeFields[2].Descriptor()
	// redeemcode.DefaultValue holds the default value on creation for the value field.
	redeemcode.DefaultValue = redeemcodeDescValue.Default.(float64)
	// redeemcodeDescStatus is the schema descriptor for status field.
	redeemcodeDescStatus := redeemcodeFields[3].Descriptor()
	// redeemcode.DefaultStatus holds the default value on creation for the status field.
	redeemcode.DefaultStatus = redeemcodeDescStatus.Default.(string)
	// redeemcode.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	redeemcode.StatusValidator = redeemcodeDescStatus.Validators[0].(func(string) error)
	// redeemcodeDescCreatedAt is the schema descriptor for created_at field.
	redeemcodeDescCreatedAt := redeemcodeFields[7].Descriptor()
	// redeemcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	redeemcode.DefaultCreatedAt = redeemcodeDescCreatedAt.Default.(func() time.Time)
	// redeemcodeDescValidityDays is the schema descriptor for validity_days field.
	redeemcodeDescValidityDays := redeemcodeFields[9].Descriptor()
	// redeemcode.DefaultValidityDays holds the default value on creation for the validity_days field.
	redeemcode.DefaultValidityDays = redeemcodeDescValidityDays.Default.(int)
	securitysecretMixin := schema.SecuritySecret{}.Mixin()
	securitysecretMixinFields0 := securitysecretMixin[0].Fields()
	_ = securitysecretMixinFields0
	securitysecretFields := schema.SecuritySecret{}.Fields()
	_ = securitysecretFields
	// securitysecretDescCreatedAt is the schema descriptor for created_at field.
	securitysecretDescCreatedAt := securitysecretMixinFields0[0].Descriptor()
	// securitysecret.DefaultCreatedAt holds the default value on creation for the created_at field.
	securitysecret.DefaultCreatedAt = securitysecretDescCreatedAt.Default.(func() time.Time)
	// securitysecretDescUpdatedAt is the schema descriptor for updated_at field.
	securitysecretDescUpdatedAt := securitysecretMixinFields0[1].Descriptor()
	// securitysecret.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	securitysecret.DefaultUpdatedAt = securitysecretDescUpdatedAt.Default.(func() time.Time)
	// securitysecret.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	securitysecret.UpdateDefaultUpdatedAt = securitysecretDescUpdatedAt.UpdateDefault.(func() time.Time)
	// securitysecretDescKey is the schema descriptor for key field.
	securitysecretDescKey := securitysecretFields[0].Descriptor()
	// securitysecret.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	securitysecret.KeyValidator = func() func(string) error {
		validators := securitysecretDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// securitysecretDescValue is the schema descriptor for value field.
	securitysecretDescValue := securitysecretFields[1].Descriptor()
	// securitysecret.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	securitysecret.ValueValidator = securitysecretDescValue.Validators[0].(func(string) error)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = func() func(string) error {
		validators := settingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// settingDescSettingGroup is the schema descriptor for setting_group field.
	settingDescSettingGroup := settingFields[2].Descriptor()
	// setting.DefaultSettingGroup holds the default value on creation for the setting_group field.
	setting.DefaultSettingGroup = settingDescSettingGroup.Default.(string)
	// setting.SettingGroupValidator is a validator for the "setting_group" field. It is called by the builders before save.
	setting.SettingGroupValidator = settingDescSettingGroup.Validators[0].(func(string) error)
	// settingDescLabel is the schema descriptor for label field.
	settingDescLabel := settingFields[3].Descriptor()
	// setting.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	setting.LabelValidator = settingDescLabel.Validators[0].(func(string) error)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[4].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	subscriptionplanMixin := schema.SubscriptionPlan{}.Mixin()
	subscriptionplanMixinFields0 := subscriptionplanMixin[0].Fields()
	_ = subscriptionplanMixinFields0
	subscriptionplanFields := schema.SubscriptionPlan{}.Fields()
	_ = subscriptionplanFields
	// subscriptionplanDescCreatedAt is the schema descriptor for created_at field.
	subscriptionplanDescCreatedAt := subscriptionplanMixinFields0[0].Descriptor()
	// subscriptionplan.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscriptionplan.DefaultCreatedAt = subscriptionplanDescCreatedAt.Default.(func() time.Time)
	// subscriptionplanDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionplanDescUpdatedAt := subscriptionplanMixinFields0[1].Descriptor()
	// subscriptionplan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscriptionplan.DefaultUpdatedAt = subscriptionplanDescUpdatedAt.Default.(func() time.Time)
	// subscriptionplan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscriptionplan.UpdateDefaultUpdatedAt = subscriptionplanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionplanDescName is the schema descriptor for name field.
	subscriptionplanDescName := subscriptionplanFields[1].Descriptor()
	// subscriptionplan.NameValidator is a validator for the "name" field. It is called by the builders before save.
	subscriptionplan.NameValidator = func() func(string) error {
		validators := subscriptionplanDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// subscriptionplanDescValidityDays is the schema descriptor for validity_days field.
	subscriptionplanDescValidityDays := subscriptionplanFields[5].Descriptor()
	// subscriptionplan.DefaultValidityDays holds the default value on creation for the validity_days field.
	subscriptionplan.DefaultValidityDays = subscriptionplanDescValidityDays.Default.(int)
	// subscriptionplanDescValidityUnit is the schema descriptor for validity_unit field.
	subscriptionplanDescValidityUnit := subscriptionplanFields[6].Descriptor()
	// subscriptionplan.DefaultValidityUnit holds the default value on creation for the validity_unit field.
	subscriptionplan.DefaultValidityUnit = subscriptionplanDescValidityUnit.Default.(string)
	// subscriptionplan.ValidityUnitValidator is a validator for the "validity_unit" field. It is called by the builders before save.
	subscriptionplan.ValidityUnitValidator = subscriptionplanDescValidityUnit.Validators[0].(func(string) error)
	// subscriptionplanDescProductName is the schema descriptor for product_name field.
	subscriptionplanDescProductName := subscriptionplanFields[8].Descriptor()
	// subscriptionplan.ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	subscriptionplan.ProductNameValidator = subscriptionplanDescProductName.Validators[0].(func(string) error)
	// subscriptionplanDescForSale is the schema descriptor for for_sale field.
	subscriptionplanDescForSale := subscriptionplanFields[9].Descriptor()
	// subscriptionplan.DefaultForSale holds the default value on creation for the for_sale field.
	subscriptionplan.DefaultForSale = subscriptionplanDescForSale.Default.(bool)
	// subscriptionplanDescSortOrder is the schema descriptor for sort_order field.
	subscriptionplanDescSortOrder := subscriptionplanFields[10].Descriptor()
	// subscriptionplan.DefaultSortOrder holds the default value on creation for the sort_order field.
	subscriptionplan.DefaultSortOrder = subscriptionplanDescSortOrder.Default.(int)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters1 := userMixin[1].Interceptors()
	user.Interceptors[0] = userMixinInters1[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[3].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(float64)
	// userDescConcurrency is the schema descriptor for concurrency field.
	userDescConcurrency := userFields[4].Descriptor()
	// user.DefaultConcurrency holds the default value on creation for the concurrency field.
	user.DefaultConcurrency = userDescConcurrency.Default.(int)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[5].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[6].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescNotes is the schema descriptor for notes field.
	userDescNotes := userFields[7].Descriptor()
	// user.DefaultNotes holds the default value on creation for the notes field.
	user.DefaultNotes = userDescNotes.Default.(string)
	// userDescTotpEnabled is the schema descriptor for totp_enabled field.
	userDescTotpEnabled := userFields[9].Descriptor()
	// user.DefaultTotpEnabled holds the default value on creation for the totp_enabled field.
	user.DefaultTotpEnabled = userDescTotpEnabled.Default.(bool)
	userallowedgroupFields := schema.UserAllowedGroup{}.Fields()
	_ = userallowedgroupFields
	// userallowedgroupDescCreatedAt is the schema descriptor for created_at field.
	userallowedgroupDescCreatedAt := userallowedgroupFields[2].Descriptor()
	// userallowedgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	userallowedgroup.DefaultCreatedAt = userallowedgroupDescCreatedAt.Default.(func() time.Time)
	userattributedefinitionMixin := schema.UserAttributeDefinition{}.Mixin()
	userattributedefinitionMixinHooks1 := userattributedefinitionMixin[1].Hooks()
	userattributedefinition.Hooks[0] = userattributedefinitionMixinHooks1[0]
	userattributedefinitionMixinInters1 := userattributedefinitionMixin[1].Interceptors()
	userattributedefinition.Interceptors[0] = userattributedefinitionMixinInters1[0]
	userattributedefinitionMixinFields0 := userattributedefinitionMixin[0].Fields()
	_ = userattributedefinitionMixinFields0
	userattributedefinitionFields := schema.UserAttributeDefinition{}.Fields()
	_ = userattributedefinitionFields
	// userattributedefinitionDescCreatedAt is the schema descriptor for created_at field.
	userattributedefinitionDescCreatedAt := userattributedefinitionMixinFields0[0].Descriptor()
	// userattributedefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	userattributedefinition.DefaultCreatedAt = userattributedefinitionDescCreatedAt.Default.(func() time.Time)
	// userattributedefinitionDescUpdatedAt is the schema descriptor for updated_at field.
	userattributedefinitionDescUpdatedAt := userattributedefinitionMixinFields0[1].Descriptor()
	// userattributedefinition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userattributedefinition.DefaultUpdatedAt = userattributedefinitionDescUpdatedAt.Default.(func() time.Time)
	// userattributedefinition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userattributedefinition.UpdateDefaultUpdatedAt = userattributedefinitionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userattributedefinitionDescKey is the schema descriptor for key field.
	userattributedefinitionDescKey := userattributedefinitionFields[0].Descriptor()
	// userattributedefinition.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	userattributedefinition.KeyValidator = func() func(string) error {
		validators := userattributedefinitionDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userattributedefinitionDescName is the schema descriptor for name field.
	userattributedefinitionDescName := userattributedefinitionFields[1].Descriptor()
	// userattributedefinition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userattributedefinition.NameValidator = func() func(string) error {
		validators := userattributedefinitionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userattributedefinitionDescDescription is the schema descriptor for description field.
	userattributedefinitionDescDescription := userattributedefinitionFields[2].Descriptor()
	// userattributedefinition.DefaultDescription holds the default value on creation for the description field.
	userattributedefinition.DefaultDescription = userattributedefinitionDescDescription.Default.(string)
	// userattributedefinitionDescType is the schema descriptor for type field.
	userattributedefinitionDescType := userattributedefinitionFields[3].Descriptor()
	// userattributedefinition.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	userattributedefinition.TypeValidator = func() func(string) error {
		validators := userattributedefinitionDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userattributedefinitionDescOptions is the schema descriptor for options field.
	userattributedefinitionDescOptions := userattributedefinitionFields[4].Descriptor()
	// userattributedefinition.DefaultOptions holds the default value on creation for the options field.
	userattributedefinition.DefaultOptions = userattributedefinitionDescOptions.Default.([]map[string]interface{})
	// userattributedefinitionDescRequired is the schema descriptor for required field.
	userattributedefinitionDescRequired := userattributedefinitionFields[5].Descriptor()
	// userattributedefinition.DefaultRequired holds the default value on creation for the required field.
	userattributedefinition.DefaultRequired = userattributedefinitionDescRequired.Default.(bool)
	// userattributedefinitionDescValidation is the schema descriptor for validation field.
	userattributedefinitionDescValidation := userattributedefinitionFields[6].Descriptor()
	// userattributedefinition.DefaultValidation holds the default value on creation for the validation field.
	userattributedefinition.DefaultValidation = userattributedefinitionDescValidation.Default.(map[string]interface{})
	// userattributedefinitionDescPlaceholder is the schema descriptor for placeholder field.
	userattributedefinitionDescPlaceholder := userattributedefinitionFields[7].Descriptor()
	// userattributedefinition.DefaultPlaceholder holds the default value on creation for the placeholder field.
	userattributedefinition.DefaultPlaceholder = userattributedefinitionDescPlaceholder.Default.(string)
	// userattributedefinition.PlaceholderValidator is a validator for the "placeholder" field. It is called by the builders before save.
	userattributedefinition.PlaceholderValidator = userattributedefinitionDescPlaceholder.Validators[0].(func(string) error)
	// userattributedefinitionDescDisplayOrder is the schema descriptor for display_order field.
	userattributedefinitionDescDisplayOrder := userattributedefinitionFields[8].Descriptor()
	// userattributedefinition.DefaultDisplayOrder holds the default value on creation for the display_order field.
	userattributedefinition.DefaultDisplayOrder = userattributedefinitionDescDisplayOrder.Default.(int)
	// userattributedefinitionDescEnabled is the schema descriptor for enabled field.
	userattributedefinitionDescEnabled := userattributedefinitionFields[9].Descriptor()
	// userattributedefinition.DefaultEnabled holds the default value on creation for the enabled field.
	userattributedefinition.DefaultEnabled = userattributedefinitionDescEnabled.Default.(bool)
	userattributevalueMixin := schema.UserAttributeValue{}.Mixin()
	userattributevalueMixinFields0 := userattributevalueMixin[0].Fields()
	_ = userattributevalueMixinFields0
	userattributevalueFields := schema.UserAttributeValue{}.Fields()
	_ = userattributevalueFields
	// userattributevalueDescCreatedAt is the schema descriptor for created_at field.
	userattributevalueDescCreatedAt := userattributevalueMixinFields0[0].Descriptor()
	// userattributevalue.DefaultCreatedAt holds the default value on creation for the created_at field.
	userattributevalue.DefaultCreatedAt = userattributevalueDescCreatedAt.Default.(func() time.Time)
	// userattributevalueDescUpdatedAt is the schema descriptor for updated_at field.
	userattributevalueDescUpdatedAt := userattributevalueMixinFields0[1].Descriptor()
	// userattributevalue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userattributevalue.DefaultUpdatedAt = userattributevalueDescUpdatedAt.Default.(func() time.Time)
	// userattributevalue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userattributevalue.UpdateDefaultUpdatedAt = userattributevalueDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userattributevalueDescValue is the schema descriptor for value field.
	userattributevalueDescValue := userattributevalueFields[2].Descriptor()
	// userattributevalue.DefaultValue holds the default value on creation for the value field.
	userattributevalue.DefaultValue = userattributevalueDescValue.Default.(string)
	usersubscriptionMixin := schema.UserSubscription{}.Mixin()
	usersubscriptionMixinHooks1 := usersubscriptionMixin[1].Hooks()
	usersubscription.Hooks[0] = usersubscriptionMixinHooks1[0]
	usersubscriptionMixinInters1 := usersubscriptionMixin[1].Interceptors()
	usersubscription.Interceptors[0] = usersubscriptionMixinInters1[0]
	usersubscriptionMixinFields0 := usersubscriptionMixin[0].Fields()
	_ = usersubscriptionMixinFields0
	usersubscriptionFields := schema.UserSubscription{}.Fields()
	_ = usersubscriptionFields
	// usersubscriptionDescCreatedAt is the schema descriptor for created_at field.
	usersubscriptionDescCreatedAt := usersubscriptionMixinFields0[0].Descriptor()
	// usersubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersubscription.DefaultCreatedAt = usersubscriptionDescCreatedAt.Default.(func() time.Time)
	// usersubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	usersubscriptionDescUpdatedAt := usersubscriptionMixinFields0[1].Descriptor()
	// usersubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersubscription.DefaultUpdatedAt = usersubscriptionDescUpdatedAt.Default.(func() time.Time)
	// usersubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersubscription.UpdateDefaultUpdatedAt = usersubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usersubscriptionDescStatus is the schema descriptor for status field.
	usersubscriptionDescStatus := usersubscriptionFields[4].Descriptor()
	// usersubscription.DefaultStatus holds the default value on creation for the status field.
	usersubscription.DefaultStatus = usersubscriptionDescStatus.Default.(string)
	// usersubscription.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	usersubscription.StatusValidator = usersubscriptionDescStatus.Validators[0].(func(string) error)
	// usersubscriptionDescDailyUsageUsd is the schema descriptor for daily_usage_usd field.
	usersubscriptionDescDailyUsageUsd := usersubscriptionFields[8].Descriptor()
	// usersubscription.DefaultDailyUsageUsd holds the default value on creation for the daily_usage_usd field.
	usersubscription.DefaultDailyUsageUsd = usersubscriptionDescDailyUsageUsd.Default.(float64)
	// usersubscriptionDescWeeklyUsageUsd is the schema descriptor for weekly_usage_usd field.
	usersubscriptionDescWeeklyUsageUsd := usersubscriptionFields[9].Descriptor()
	// usersubscription.DefaultWeeklyUsageUsd holds the default value on creation for the weekly_usage_usd field.
	usersubscription.DefaultWeeklyUsageUsd = usersubscriptionDescWeeklyUsageUsd.Default.(float64)
	// usersubscriptionDescMonthlyUsageUsd is the schema descriptor for monthly_usage_usd field.
	usersubscriptionDescMonthlyUsageUsd := usersubscriptionFields[10].Descriptor()
	// usersubscription.DefaultMonthlyUsageUsd holds the default value on creation for the monthly_usage_usd field.
	usersubscription.DefaultMonthlyUsageUsd = usersubscriptionDescMonthlyUsageUsd.Default.(float64)
	// usersubscriptionDescAssignedAt is the schema descriptor for assigned_at field.
	usersubscriptionDescAssignedAt := usersubscriptionFields[12].Descriptor()
	// usersubscription.DefaultAssignedAt holds the default value on creation for the assigned_at field.
	usersubscription.DefaultAssignedAt = usersubscriptionDescAssignedAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
